### ISSUE TITLE
WafLogBucket not encrypted in template

### ISSUE THREAD

**Issue by aldegoeij** [awslabs/aws-waf-security-automations#109]
The `WafLogBucket` resource for the `HttpFloodProtectionLogParser` option is not encrypted by default, resulting in a bucket with WAF logs and Athena result sets in the clear.

https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/deployment/aws-waf-security-automations.template#L357-L368

Adding AES256 encryption as minimum encryption level (I imagine KMS implementations differ per user) min upcoming PR.

**Comment by georgebearden** [comment]
This should have been addressed in the latest update to this solution. Please let us know if you need additional assistance around this.
