### ISSUE TITLE
strange Physical ID for WafWebAclRuleControler

### ISSUE THREAD

**Issue by ericjacques** [awslabs/aws-waf-security-automations#11]
Hello, 

As I see the **Physical ID** in Ressources for **WAF** are like 
**xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxx**.
But for the WafWebAclRuleControler the  **Physical ID** is:
**2017/05/23/[$LATEST]xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx**
So the logs name too.

I didn't found in the console neither in the code why, it don't seems to perturb the system, but I don't tryed it in prod for now.

**Comment by hvital** [comment]
Hi ericjacques. Didn't get what should be fixed. 
Is there something that should be clarified in solution's doc?

**Comment by ericjacques** [comment]
Hi Heitor,
You can see the "problem" in cloudFormation, Stack Name: <my waf stack>, tab: Ressources (scroll at the bottom).

For now the consequence of this is in logs, when someting is reported, I have something like:
See the details in CloudWatch Log Stream: 2017/05/23/[$LATEST]xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

**Comment by hvital** [comment]
HI @ericjacques 

I forgot to mention that we added the complete CloudWatch logs link in case of error. Instead of having to figure out which group/stream you should open, you now can just follow the link printed on CloudFormation Event Tab's log.

**Comment by groverlalit** [comment]
Hi @ericjacques 
Can you please advise if we you have the answers you were looking for? If yes, can this ticket can be closed?

**Comment by ericjacques** [comment]
Too much time has passed since then so, let's close the ticket.
