### ISSUE TITLE
Update the docmentation

### ISSUE THREAD

**Issue by karkohli** [awslabs/aws-waf-security-automations#115]
Solution document does not give insight if it will create WAF classic or WAFv2 with Shield. One of the customers suggested to update the document stating specifically that the source code is for WAF classic.

https://aws.amazon.com/solutions/aws-waf-security-automations/

**Comment by georgebearden** [comment]
Hi - This should have been addressed in the latest update to this solution. Please let us know if you need additional assistance around this.
