### ISSUE TITLE
More semver-y semver

### ISSUE THREAD

**Issue by zingyb** [awslabs/aws-waf-security-automations#116]
I'm noticing a trend of many breaking changes on every patch-level update. It's like every time there's a new update the repo is re-architected. Would the maintainers be willing to adopt a more semver-y versioning scheme so that we can easily see when the repo is changing drastically?

Thanks!

**Comment by tomnight** [comment]
Thanks for the feedback, 

We have made a number of improvements to our deployment process and have standardized the structure of our solutions repos. Part of these changes include moving to a schematic versioning style so hopefully the extent of any future updates will be more clear.
