### ISSUE TITLE
Anonymous usage not sent to Amazon

### ISSUE THREAD

**Issue by 0xdabbad00** [awslabs/aws-waf-security-automations#13]
Anonymous usage data is sent to awssolutionsbuilder.com according to
https://github.com/awslabs/aws-waf-security-automations/blob/beca5eb31b55dcba291b5ad1a91a0ba687292402/source/custom-resource/custom-resource.py#L423

This field is described as "Send anonymous data to AWS to help us understand solution usage across our customer base as a whole" according to https://github.com/awslabs/aws-waf-security-automations/blob/beca5eb31b55dcba291b5ad1a91a0ba687292402/deployment/aws-waf-security-automations-alb.template#L113

This data is not being sent to AWS, but instead is being sent to some third-party vendor, which you may not trust, even if the data is anonymous.  Given that this project is hosted in the awslabs account, this affiliation with a third-party vendor is uncomfortable.  I believe this usage reporting should be removed completely.

**Comment by eric5102** [comment]
@0xdabbad00 that domain belongs to AWS not a third party:

Registrant Name: Hostmaster, Amazon Legal Dept.
Registrant Organization: Amazon Technologies, Inc.

**Comment by hvital** [comment]
'https://metrics.awssolutionsbuilder.com/generic' is an endpoint of the team who manage 'https://aws.amazon.com/answers/' solutions.
