### ISSUE TITLE
WAF ACLs, IP rules, etc not shown (not created?) on AWS WAF Console 

### ISSUE THREAD

**Issue by cscareerkaizen** [awslabs/aws-waf-security-automations#132]
I followed the guide (https://docs.aws.amazon.com/solutions/latest/aws-waf-security-automations/deployment.html) which created two CF stacks successfully. 

Since we use ALB not CF, I chose ALB.

But when I go to AWS WAF Console, I see no WAF resources shown. Even if I picked us-east-1, nothing shown.

If I go to EC2 console and pick ALB, it says "this ALB not WAF protected"

<img width="1315" alt="Screen Shot 2020-06-04 at 10 26 23 PM" src="https://user-images.githubusercontent.com/65804592/83776644-9c023000-a6b2-11ea-93fb-0dfc33f71241.png">
<img width="1167" alt="Screen Shot 2020-06-04 at 10 25 29 PM" src="https://user-images.githubusercontent.com/65804592/83776661-a0c6e400-a6b2-11ea-841f-019778a36117.png">
<img width="1069" alt="Screen Shot 2020-06-04 at 10 25 19 PM" src="https://user-images.githubusercontent.com/65804592/83776663-a15f7a80-a6b2-11ea-9031-f33e9a1a0db7.png">
<img width="904" alt="Screen Shot 2020-06-04 at 10 24 22 PM" src="https://user-images.githubusercontent.com/65804592/83776667-a290a780-a6b2-11ea-93e8-98f43adf7160.png">

**Comment by rakshb** [comment]
Hello @cscareerkaizen,
Thanks for reaching out. Are you using V2.3.2? This version supports AWS WAF Classic. 

If you go to AWS WAF on console, by default it shows the WAFv2 UI. You will have to switch to WAF Classic (you can make the selection in the blue banner as shown in the picture)
You will be able to find your WAF security automation related resources under WAF Classic UI.

![image](https://user-images.githubusercontent.com/64986166/84051480-37c6c100-a97d-11ea-9a29-5d4f3157ab64.png)


We are also working on a new version of WAF Security Automations to support WAFv2 and will be releasing it shortly.

**Comment by cscareerkaizen** [comment]
I see it in WAF classic but not from ELB integrated services @rakshb 

<img width="883" alt="Screen Shot 2020-06-11 at 10 23 17 PM" src="https://user-images.githubusercontent.com/65804592/84405406-4558a100-ac32-11ea-952b-27c71f61bbc2.png">

**Comment by peteroruba** [comment]
@cscareerkaizen to attach a WAF ruleset to your ALB go to "AWS Firewall Manager" -> "AWS WAF Classic" ->  Select "Web ACLs" (under left hand side menu items) -> Select your region at "Filter" -> Select your Web ACL -> Then select the tab "Rules" -> At the bottom you'll find a button "Add association" which lets you attach your Web ACL ruleset to a load balancer.

**Comment by rakshb** [comment]
Thanks @peteroruba! Give us a thumbs up when you are able to set up the association successfully @cscareerkaizen

**Comment by cscareerkaizen** [comment]
Yes, was able to. Thanks!

**Comment by dclose20** [comment]
@rakshb Do you have any timeline on the WAFv2 support? I'm interested in implementing this solution, but would rather hold off until then. Thanks!!

**Comment by rakshb** [comment]
@dclose20 We released WAF V3.0 last week with support for WAFv2 API. Check it out on https://aws.amazon.com/solutions/implementations/aws-waf-security-automations/
