### ISSUE TITLE
Error occurred while GetObject. S3 Error Code: NoSuchKey

### ISSUE THREAD

**Issue by lngphp** [awslabs/aws-waf-security-automations#135]
I'm having an issue:

> Error occurred while GetObject. S3 Error Code: NoSuchKey. S3 Error Message: The specified key does not exist. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 1e25ca58-b420-458b-bdef-fbb3c029f47a)

I'm executing CloudFormation Stack in the same region as S3.

**Comment by aijunpeng** [comment]
Can you please provide the following information to help our investigation? Thanks!
1. Which region were you trying to launch the stack? 
2. Input parameter values for your stack
3. Error screenshot including event steps
4. Were you using an existing or new s3 bucket?

**Comment by lngphp** [comment]
Hi!

Thanks for the response!
This time the deployment went smooth - cannot reproduce it. Please close this issue.

**Comment by Loic-Hakisa** [comment]
Hello,
Same problem on eu-central-1 frankfurt region...
Like you can see I tried with public access open on s3 template bucket, but no way to make it working

Any idea please ?

Best Regards,
Loïc

![WAF-S3-template-buckets](https://user-images.githubusercontent.com/63661291/88943310-9c224480-d28b-11ea-95d5-b4f28dadd7b7.PNG)
![WAF-Enabling](https://user-images.githubusercontent.com/63661291/88943316-9cbadb00-d28b-11ea-925a-4fa22f993e6f.PNG)
![WAF-Enabling-bug](https://user-images.githubusercontent.com/63661291/88943326-9d537180-d28b-11ea-979b-665347076eef.PNG)
