### ISSUE TITLE
Honeypot feature add CloudFront IP to Bad Bot IP List

### ISSUE THREAD

**Issue by peteroruba** [awslabs/aws-waf-security-automations#136]
Hello,
I have deployed the Honeypot feature and defined both an Origin and Behavior in my CloudFront distribution. When I issue a request to the Honeypot path I see a CloudFront IP (64.252.82.168/32) being added to the Bad Bot IP list instead of my actual IP. 

As per https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html the aforementioned IP belongs to AWS:

    {
      "ip_prefix": "64.252.82.0/24",
      "region": "eu-west-2",
      "service": "AMAZON",
      "network_border_group": "eu-west-2"
    },

**Comment by aijunpeng** [comment]
What is the version of the solution you are using?

**Comment by peteroruba** [comment]
@aijunpeng I am using v2.3.3

**Comment by aijunpeng** [comment]
Bad bot lambda (access-handler.py) extracts the source ip(event['requestContext']['identity']['sourceIp']) from the response returned by the request. Can you see what source ip is in cloudwatch logs for the lambda? Also please provide detailed steps on how you configured your honeypot link in your web app and how you issued your request to help our investigation. Thank you!

**Comment by peteroruba** [comment]
Hi @aijunpeng, sorry for the late response. My setup ist as follows:
- CloudFront distribution deployed via a CloudFormation stack in eu-central-1
- AWS WAF Security Automations deployed in us-east-1
- Modified the reference to API Gateway Hostname in CloudFront stack (eu-central-1):
-- I did not set up a link in our webapp, the only thing I have configured is a CloudFront Behavior (set to  /.git/*   ) and CloudFront Origin (set to Bad Bot API Gateway)
- Manually entered the afore mentioned CloudFront distribution in AWS WAF as the associated resource

CloudWatch Logs output for the bad bot Lambda say: sourceIp': '64.252.86.180'

The request was issued from the terminal via curl to the honeypot url ("/.git/")

**Comment by aijunpeng** [comment]
Thanks for the detailed information. I followed your steps and ran a test. My test worked as expected - my actual sourceip instead of cloudfront ip was added to the bad bot ip set. What does your CloudFront distribution look like after you "Modified the reference to API Gateway Hostname in CloudFront stack (eu-central-1)"? Please send a screenshot that shows its configurations. You can go to AWS CloudFront console -> select distribution  -> take a screenshot of the page. Also please send a screenshot of your CloudFront origin. You can select Origins and Origin Groups tab -> select the origin -> Edit -> take a screenshot of the Edit Origin page. Lastly, I would suggest you to manually create a CloudFront distribution via AWS console instead of using CloudFormation stack for testing purpose. After creating the distribution, create origin by following steps here: https://docs.aws.amazon.com/solutions/latest/aws-waf-security-automations/deployment.html#step3. Ignore step 8 and 9 if you don't want to set up robots.txt file to disallow your web application to access to the honeypot link.

**Comment by peteroruba** [comment]
@aijunpeng  I'm sorry, I forgot to mention that I deployed version v.3.0.0 this time. Either way, the observed effect is the same.

I am attaching a set of screenshots.

<img width="1203" alt="waf0" src="https://user-images.githubusercontent.com/5119296/88894159-c18d5f00-d247-11ea-88d8-8b2b1dd59f94.png">
<img width="908" alt="waf1" src="https://user-images.githubusercontent.com/5119296/88894171-c520e600-d247-11ea-88ba-2d497179b9c7.png">
<img width="693" alt="waf2" src="https://user-images.githubusercontent.com/5119296/88894175-c6521300-d247-11ea-8bee-265edae358d9.png">
<img width="683" alt="waf3" src="https://user-images.githubusercontent.com/5119296/88894176-c6eaa980-d247-11ea-832a-38818c8972c1.png">
<img width="1336" alt="waf5" src="https://user-images.githubusercontent.com/5119296/88894179-c6eaa980-d247-11ea-883e-9824c3009f58.png">
<img width="1334" alt="waf6" src="https://user-images.githubusercontent.com/5119296/88894182-c7834000-d247-11ea-99f5-fa87c20afb85.png">

**Comment by peteroruba** [comment]
One interesting observation - WAF sees my actual IP, when check the details of a sampled request:

<img width="820" alt="waf8" src="https://user-images.githubusercontent.com/5119296/88897839-39f61f00-d24c-11ea-9a6f-0643bd93ae1f.png">

**Comment by aijunpeng** [comment]
Thanks for all the information! The cloudfront configurations on your screenshots look fine. I mimicked your configurations and ran another test. It worked for me again. I would suggest you to delete all ips from the badbot ip set to do a fresh test. Also what was the ip in the message returned by your curl command?  The message is like "{"message": "[your ip] Thanks for the visit."}.  That ip is the one should be added to the badbot ip set. You can also get the message by going to AWS CloudFormation Console -> select your waf stack -> select Outputs tab -> click on the honeypot link. 

I would also like a copy of the cloudwatch logs for your badbot lambda function if the issue remains.

**Comment by peteroruba** [comment]
Output from curl accessing the honeypot URL in our application (via CloudFront):
message: [64.252.86.241] Thanks for the visit.* Closing connection 0
(CloudFront IP)

Output from curl accessing the honeypot URL in API Gateway:
message: [94.231.XXX.XX] Thanks for the visit.* Closing connection 0
(My actual IP)

**Comment by peteroruba** [comment]
Attaching the badbot lamda logs (replaced my actual IP with "1.1.1.1")


[badbotlambdalogs.zip](https://github.com/awslabs/aws-waf-security-automations/files/5009975/badbotlambdalogs.zip)

**Comment by peteroruba** [comment]
@aijunpeng I noticed that the Lambda logs from the test via CloudFront show my actual IP in "X-Forwarded-For".

**Comment by aijunpeng** [comment]
Thanks for the information. It is very helpful. Finally I am able to reproduce the issue and found out the reason for the issue. It is a bug in the code. We have added it to our backlog and will fix it in our future release. For now, if you can, as a workaround you can manually modify your badbot lambda (access-handler.py) to fetch "X-Forwarded-For" ip for requests from cloudfront. Below is the basic logic for the fix:

1. When event['requestContext']['identity’][‘userAgent’] == ‘Amazon CloudFront’, fetch X-Forwarded-For[0] ip:
        source_ip = event['headers']['X-Forwarded-For'].split(',')[0].strip()
 2. For other cases, use sourceip:
        source_ip = str(event['requestContext']['identity']['sourceIp’])

I apologize for the inconvenience. Thanks again for reporting the issue!

**Comment by aijunpeng** [comment]
Thanks for the information. It is very helpful. Finally I am able to reproduce the issue and found out the reason for it. It is a bug in the code. We have added it to our backlog and will fix it in our future release. For now, if you can, as a workaround you can manually modify your badbot lambda (access-handler.py) to fetch "X-Forwarded-For" ip for requests from cloudfront. Below is the basic logic for the fix:

1. When event['requestContext']['identity’][‘userAgent’] == ‘Amazon CloudFront’, fetch X-Forwarded-For[0] ip:
     source_ip = event['headers']['X-Forwarded-For'].split(',')[0].strip()
2. For other cases, use sourceip:
     source_ip = str(event['requestContext']['identity']['sourceIp’])

I apologize for the inconvenience. Thanks again for reporting the issue!

**Comment by peteroruba** [comment]
@aijunpeng thank you so much for your assistance. I confirm the issue has been resolved.

**Comment by Patrick-56Bit** [comment]
I have the same issue. @aijunpeng can you confirm whether this will be resolved soon?

**Comment by aijunpeng** [comment]
@Patrick-56Bit I don't have an ETA. It is in our backlog and should be addressed when we release our next solution update. I apologize for the inconvenience. There is a workaround above that you can try.

**Comment by burnzy** [comment]
Looks like this issue was caused by this PR that was done for security reasons: https://github.com/awslabs/aws-waf-security-automations/pull/123

**Comment by estahn** [comment]
@aijunpeng Any updates on this?

**Comment by dcopestake** [comment]
I've raised pull request #195 which attempts to address this by changing to use an injected header of `True-Client-Ip` instead (via a CloudFront function). Seems to be doing the trick for me.

**Comment by aijunpeng** [comment]
Thanks for your contribution. We have added your request to our solution backlog items and it will be evaluated in future
solution releases.
