### ISSUE TITLE
LogParser Creation Error 

### ISSUE THREAD

**Issue by pineros** [awslabs/aws-waf-security-automations#137]
I'm attempting to create WAF rules using the AWS provided CloudFormation template found here: https://aws.amazon.com/solutions/implementations/aws-waf-security-automations/

I am using the default values (with the exceptions being ALB endpoint and access log bucket name). I am receiving this error:

`1 validation error detected: Value 'This function parses access logs to identify suspicious behavior, such as an abnormal amount of errors. It then blocks those IP addresses for a customer-defined period of time. Parameters: 100, 50 and 240. ' at 'description' failed to satisfy constraint: Member must satisfy regular expression pattern: .* (Service: AWSLambdaInternal; Status Code: 400; Error Code: ValidationException;
`

I have successfully launched the same CloudFormation template in another account last week using the provided AWS defaults. I'm not sure what changed between last week and now. Could you please provide some insight in what I'm doing wrong?

**Comment by aijunpeng** [comment]
This issue seems to  have been caused by some internal service issue and it should be fixed now. Please try again and let us know if there are any more issues. Thank you!

**Comment by pineros** [comment]
Everything is working now! Thanks for your help!
