### ISSUE TITLE
Cannot add the List of IP Addresses to WAFWhitelistSetV4

### ISSUE THREAD

**Issue by lngphp** [awslabs/aws-waf-security-automations#141]
**Describe the bug**
After adding the list IP addresses to `aws-waf-security-automations-webacl.template:Resources.WAFWhitelistSetV4.Addresses`, I got:

`Embedded stack arn:aws:cloudformation:us-west-1:*:stack/WAF-XX-DEV-WebACLStack-XXX/7f8ad140-c834-11ea-a83c-066e55aa410d was not successfully created: The following resource(s) failed to create: [TimerBlackV4, WAFWhitelistSetV4].
`

**To Reproduce**
Add the list of addresses like:

```
  Addresses
       - '192.168.1.1/32'
       - '192.168.1.2/32'
```

**Expected behavior**
The list  of IP addresses is populated to ACL Rule.

- [v2.3.3] Version
- [us-west-1] Region
- [Yes ] Was the solution modified from the version published on this repository?
- [https://gist.github.com/lngphp/1e306702b812178768cddd529f0958a1] If the answer to the previous question was yes, are the changes available on GitHub?

**Screenshots**
[https://imgur.com/znHhF5v](url)

**Additional context**
How to add the list of IP addresses to WhiteListALcl?

**Comment by aijunpeng** [comment]
Thanks for the comment. Can you please clarify a few things?
1. Which version of the waf solution are you using? The error message indicates v3.0, but it says v2.3.3 in the ticket.
2. What are the exact steps you took to get the error? The error message seems a stack creation error, then how did you get to add ip without stack being deployed successfully first?

**Comment by aijunpeng** [comment]
3. Provide error screenshots - The screenshots link in the ticket doesn't work and shows no match found.

**Comment by lngphp** [comment]
The issue relates to SOLUTION_NAME variable value. If you set it not to "aws-waf-security-automations", this issue appears.

**Comment by aijunpeng** [comment]
If you were building your own deployment assets by following the instructions in readme, you should be able to change value for SOLUTION_NAME. Just make sure you change all references to SOLUTION_NAME in your commands such as uploading assets to s3, etc. However this is just my speculation since I don't have sufficient information to know what you were doing exactly. Please kindly provide all required details if you would like further help with this.

**Comment by maykays** [comment]
Closing this issue. Please re-open if the problem persists.
