### ISSUE TITLE
Deploy stack failed on eu-central-1

### ISSUE THREAD

**Issue by Loic-Hakisa** [awslabs/aws-waf-security-automations#144]
Hello,
Problem when creating the stack on eu-central-1 frankfurt region (S3 bucket and Cloudformation stack in same region)
Like you can see I tried with public access open on s3 template bucket, but no way to make it working

Any idea please ?

![WAF-S3-template-buckets](https://user-images.githubusercontent.com/63661291/88944179-b6105700-d28c-11ea-9a51-aab4fea6ba50.PNG)
![WAF-Enabling](https://user-images.githubusercontent.com/63661291/88944182-b6a8ed80-d28c-11ea-8dd7-d88d73c59eb9.PNG)
![WAF-Enabling-bug](https://user-images.githubusercontent.com/63661291/88944186-b7418400-d28c-11ea-81e4-ee6913736715.PNG)

Best Regards,
Loïc

**Comment by lampier** [comment]
Is the firewall-frankfurt-access bucket created? The cloud formation does not create it for you, you have to create it first. The bucket image you provided does not contain it, and yes other buckets.

**Comment by Loic-Hakisa** [comment]
Hello and thank you,

I have exactly the same problem when creating this bucket, and the same error if I set "Activate Scanner and Probe protection" to false and then without using this access bucket....

Any Idea ?

Best regards,
Loic

**Comment by praveenis** [comment]
Hi @Loic-Hakisa , 

We were not able to reproduce this issue with given input parameter in Frankfurt region. Can you please share this addition information to troubleshoot this issue.

what version of waf-security-automations solution you are trying to install? Also please share the template url ?

Thanks,
Praveen

**Comment by CameronMcAuley** [comment]
@Loic-Hakisa 

Here is your issue, I think:
https://github.com/awslabs/aws-waf-security-automations/issues/154

**Comment by Loic-Hakisa** [comment]
Big thanks for this reply, I will check it soon !

Cordialement,


*Loïc EHRHART                             *

DevOps

Tél : +33 6 12 18 79 65


Value your digital communities





Le mar. 8 sept. 2020 à 16:17, Cameron McAuley <notifications@github.com> a
écrit :
