### ISSUE TITLE
AWSWAFSecurityAutomations-LambdaWAFReputationLists rule input does not allow additions due to length constraint

### ISSUE THREAD

**Issue by FireballDWF** [awslabs/aws-waf-security-automations#15]
The error "There was an error while saving rule AWSWAFSecurityAutomations-LambdaWAFReputationLists-BPSIVMXJZJP6.
Details: 1 validation error detected: Value 'AWSEvents_AWSWAFSecurityAutomations-LambdaWAFReputationLists-BPSIVMXJZJP6_LambdaWAFReputationListsParserFunction' at 'statementId' failed to satisfy constraint: Member must have length less than or equal to 100." is received when attempting to add add another URL, such as {"url":"https://reputation.alienvault.com/reputation.generic"}
to the lambda functions' Constant JSON text field. 

Suggested fix is to have the Cloudformation store the contents of this input in an S3 bucket, then have the lambda function get the json text from S3, which will enable users to add more lists

**Comment by hvital** [comment]
Got it. Added a task to review this for the next version. Quick question: is this alienvault rep list open to be used? Was thinking to add it in the original template.

**Comment by FireballDWF** [comment]
Yes.  "When we launched the Open Threat Exchange (OTX) project, one of our goals was creating an open and free threat database and exchange system. We want it to be used by as many users as possible using a wide range of technologies." per https://www.alienvault.com/blogs/labs-research/feeding-alienvaults-open-threat-exchange-otx-threat-information-to-arcsight

**Comment by eberkut** [comment]
Has this been fixed at any point? I'm building my own lists through MineMeld (https://github.com/PaloAltoNetworks/minemeld/) and I'm hitting the same error.

**Comment by stevemorad** [comment]
Fixed in v2.1

**Comment by jeremygaither** [comment]
@stevemorad what was the fix? Still seeing this issue...

**Comment by piether** [comment]
I'm also experiencing this issue
