### ISSUE TITLE
Lambda function for populating IP reputation list not necessary for WAFv2, manged rule can be used istead

### ISSUE THREAD

**Issue by obounaim** [awslabs/aws-waf-security-automations#151]
Deploying the Lambda function to populate the IP reputation list is no longer necessary for WAFv2
This Lambda should be replaced with the manged rule named :  AWSManagedRulesAmazonIpReputationList

https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html

**Comment by aijunpeng** [comment]
Thanks for submitting the ticket. It would be nice to simplify the solution, however since the WAF service managed rule and WAF solution use different sources to populate reputation list we would still need the reputation list function in the solution.

**Comment by gavinclarkeuk** [comment]
Just out of interest - why have different sources for what is apparently the same thing? Sounds like you would always want both in a robust solution, but it might not be obvious to people deploying this solution that they should also deploy the managed rule
