### ISSUE TITLE
Change pip to pip3 in build-s3-dist.sh

### ISSUE THREAD

**Issue by CameronMcAuley** [awslabs/aws-waf-security-automations#153]
**Is your feature request related to a problem? Please describe.**
- The README makes it clear that the dependencies for these automations include Python 3.8
- However, some people may still have two different versions of Python installed, with `pip` pointing to Python 2.7.
- The build-s3-dist.sh script uses `pip` and therefore all packages could be installed with Python 2.7 accidentally

**Describe the feature you'd like**
- Force Python 3.x package installation by changing `pip` to `pip3` in build-s3-dist.sh

**Comment by aijunpeng** [comment]
Thanks for your contribution. We have added your request to our backlog and it will be considered in future releases as needed.

**Comment by dscpinheiro** [comment]
Hi!

We just released [v3.2.0](https://github.com/awslabs/aws-waf-security-automations/releases/tag/v3.2.0) of the solution, and this issue has been fixed.
