### ISSUE TITLE
Lambda errors (false positive)

### ISSUE THREAD

**Issue by ghost** [awslabs/aws-waf-security-automations#16]
The experience is positive so far but a lot of time is lost investigating false errors. For example the first Lambda error I noticed in CW logs was `An error occurred (403) when calling the HeadObject operation: Forbidden`  but this is simply because there is no file named aws-waf-security-automations-current-blocked-ips.json in the bucket. Then I started seeing errors like `[send_anonymous_usage_data] Error to get Num Allowed Requests`, etc.

This is just caused by code using errors as expected code behavior and reporting them as true errors. This is an excellent package but the error handling should be improved to provide a better experience. Hunting ghosts because you see lots of errors and don't know which can be ignored is not fun.

**Comment by hvital** [comment]
We've just pushed a new version. All prints were substituted by logging.getLogger().[debug or info or error].

Thanks.
