### ISSUE TITLE
Add parameter for an IAM Permission boundary for the role creations

### ISSUE THREAD

**Issue by maykays** [awslabs/aws-waf-security-automations#161]
Please up-vote if you want this feature. Do not submit a new feature request.

**Comment by pkennedyvt** [comment]
This is working in two production environments for me.  The PR is here:  https://github.com/awslabs/aws-waf-security-automations/pull/176

**Comment by mfcze** [comment]
Hi there, would you pls provide an update where we are with this little tweak required which would be highly appreciated by many customers where permission boundaries are in use. pkennedyvt has made the code adjustment ready.

Thanks for your feedback.

**Comment by maykays** [comment]
Thank for your suggestion. We do not plan to implement this feature in the near-term. Feel free to clone the github repo and add your own customizations for the time being.
