### ISSUE TITLE
Suggestion: add notification

### ISSUE THREAD

**Issue by eric5102** [awslabs/aws-waf-security-automations#17]
I am interested to add notifications when changes are made to the Auto-Block list. I can do it by editing the code and adding optional support for SNS notifications or I can try using CW Events to call yet another Lambda function to filter events I am interested in and then use SNS.

Solution #1 is easiest but makes it harder to deploy updates of the waf-automation code
Solution #2 is decoupled but requires more work and a second CF template is needed for deployment

Is there a third solution I have not thought of? Or can #1 be added as an option to the waf-automation code? It seems a natural fit to me

**Comment by hvital** [comment]
That's SNS notification can be added using CloudWatch logs alarm (filtering Log Parser logs when a new IP is added). I don't know if I show add this as an optional feature or default feature for all new created stack. What do you think?

As for the solution version, we are always publishing the solution packs here: 
https://aws.amazon.com/answers/security/aws-waf-security-automations/

**Comment by eric5102** [comment]
Unless I am missing something a CloudWatch alarm will simply be triggered by the custom metric on the parser logs but doing it this way we lose the information on what IP was added. My interest on adding it to the parser directly is because we retain useful information:

# the exact IP that was added (or removed)
# the exact source that triggered this action

If we have 100 web sites using the same WAF configuration and configure each CloudFront distribution to log with a different prefix to the same bucket the key that triggered the action also tells me which site is the origin. That does help speed up investigation when it is necessary. Notification on a metric loses  this information or at least makes it harder to get to

**Comment by hvital** [comment]
Got it. I'll add a CF parameter to ask if the user want to be notified when IPs are added/removed from Auto Block Rule. 

BTW: Did you see RBR? More info: https://aws.amazon.com/about-aws/whats-new/2017/06/aws-announces-rate-based-rules-for-aws-waf/

Our idea is to added this feature tho Security Automation stack as soon as we get CloudFormation support for that feature.

**Comment by eric5102** [comment]
Thank you!

Yes I did see RBR and yes there is high interest.

**Comment by stevemorad** [comment]
RBR added in v2.1

**Comment by jeffneuen** [comment]
Sorry to revive an old issue, but was the CF parameter to ask if the user want to be notified when IPs are added/removed from Auto Block Rule ever added to the template? Can't see it anywhere, and wondered if I was missing something.
