### ISSUE TITLE
How to handle stack updates

### ISSUE THREAD

**Issue by eric5102** [awslabs/aws-waf-security-automations#19]
I see `custom-resource.py` is handling stack update in a destructive manner:

```
def update_stack(stack_name, resource_properties):
    print("[update_stack] Start")
    delete_stack(stack_name, resource_properties)
    create_stack(resource_properties)
    print("[update_stack] End")
```

Is there a reason to do it this way? With this any changes made to the whitelist and any additional custom waf rules we add will be lost. Of course there doesn't seem anything to invoke updates on custom resources or I missed it.

Can we have some guidance on managing updates to this stack without any data loss? We do edit the stack and deploy additional rules but even without those there is a risk of data loss

**Comment by stevemorad** [comment]
Added force_delete parameter in v2.1
