### ISSUE TITLE
Error in log parser for uriList (expiration check)

### ISSUE THREAD

**Issue by mrabczuk** [awslabs/aws-waf-security-automations#192]
Version 3.1.0
Function: merge_outstanding_requesters()

The expiration check in urlList section is using "general" key from config:
 **elif total_diff_min < config['general']['blockPeriod']**

while it should be using "uriList" key path e.g. **config['uriList'][uri]['blockPeriod']**

**Comment by aijunpeng** [comment]
Thanks for the comment. block period is a general configuration by design. What does your config file look like? Are you getting any errors? Please elaborate so we can better understand the issue.
