### ISSUE TITLE
Error on rollback - WAFReputationListsSet

### ISSUE THREAD

**Issue by kunal999** [awslabs/aws-waf-security-automations#194]
**Describe the bug**
Upon trying to create a new stack, there was an error due to S3's limitation of only being able to create a single event notification on an S3 bucket with overlapping prefixes/suffixes (FYI: this should be noted in the considerations section of the documentation).
The stack started a rollback, however, the rollback failed upon trying deletion of WAFReputationListsSet.
Error message:-
Operation would result in exceeding resource limits. (Service: AWSWAF; Status Code: 400; Error Code: WAFLimitsExceededException; Request ID: 45db77d3-c43a-4bf9-b2b9-46dd41cf5482; Proxy: null)

**To Reproduce**
- Try to engineer a rollback by simulating a condition such as the S3 event notification conflict mentioned above
- Rollback should fail

**Expected behavior**
Rollback should succeed and the whole stack including all resources should be deleted.

**Please complete the following information about the solution:**
- [ ] Version: 2.3.3

- [ ] Region: us-west-2
- [ ] Was the solution modified from the version published on this repository? No

**Comment by aijunpeng** [comment]
Thanks for reporting the issue. It's likely been caused by exceeding the WAF classic service api call limit. The issue should be transitory. Can you delete the stack again and see if it succeeds this time?

**Comment by kunal999** [comment]
Yeah deletion works, thanks
