### ISSUE TITLE
Guide for a seamless way to update WAF application

### ISSUE THREAD

**Issue by saadsheikhaws** [awslabs/aws-waf-security-automations#196]
My customer has v2.x.x of this application currently deployed but they want to update to v3.x.x due to Nodejs10.x support ending soon on Lambda. Can you guide what's the correct way to update the application? Should we just go on and deploy the new template, or update the old template with the new one in Cloudformation.
They are not using any customisation currently.

**Comment by aijunpeng** [comment]
Thanks for the inquiry. The correct way is to deploy the WAF v3.x solution as a new stack. The WAF v2.x solution supports WAF Classic API calls while v3.x supports the latest WAFv2. Once v3.x is deployed, customer should switch to WAFv2 console to view all the resources that are created by the solution. 

Implement Guide:
https://docs.aws.amazon.com/solutions/latest/aws-waf3-security-automations/welcome.html
