### ISSUE TITLE
SAM deployment support

### ISSUE THREAD

**Issue by koen-serneels** [awslabs/aws-waf-security-automations#199]
Currently some manual actions are required to deploy the solution such as creating s3 buckets, uploading the artifacts and then triggering CFN to deploy the stack. It would be more interesting to make use of the SAM deployment model so that all this is done automatically. It would also fit better when this project is used from newer projects where mostly SAM is already in u se

**Comment by aijunpeng** [comment]
Thanks for the request. This solution provides an out-of-box stack and source code for customization. To deploy the out-of-box solution, you simply launch the cloudformation stack, no manual actions are required. If you choose to customize the source code, then you would need to take manual steps to build your own stack.
