### ISSUE TITLE
Ability to have QueryScheduledRunTime as a parameter in CloudFormation template

### ISSUE THREAD

**Issue by hakkurt** [awslabs/aws-waf-security-automations#211]
**Is your feature request related to a problem? Please describe.**
QueryScheduledRunTime is set to 5 minutes by default, this interval is too long for some Customer, Even it can be change directly from CloudFormation template yaml, it will be easier to change if this can be part of CloudFormation parameter
**Describe the feature you'd like**
can QueryScheduledRunTime be part of CloudFormation parameter ?
**Additional context**

**Comment by aijunpeng** [comment]
Thanks for submitting the request. This is done by design. We'd like to provide a way for customers to update QueryScheduledRunTime as needed as well as restrain the number of input parameters from getting too high. Allowing customers to update the value inside the template achieves both goals.
