### ISSUE TITLE
Whitelisting some application URL's

### ISSUE THREAD

**Issue by MariDavila** [awslabs/aws-waf-security-automations#22]
Hi,
I've deployed this solution to test it with our application and so far so good. I have one concern regarding the log reader lambda function and DDos attack protection. There are several URL's in our application that generate numerous page requests; we don't want to add IP's making those requests to end up blocked. Is there a way to "whitelist" application URL's? I only see a way to whitelist IP adresses.

Thanks.

**Comment by eric5102** [comment]
You have to create more rules. This is what we did and it works well. The only scary problem is you quickly reach the 10 limit. We can live with the current limit but any site attack that targets specific resources or use specially crafted url/querystr may be difficult to block. I hope they increase that limit or start supporting OR in rules (or both :-))

**Comment by MariDavila** [comment]
Cool, so, no necessarily modify the out of box AWSWAFSecurityAutomatons rules, but create additional rules that let thru certain URLS? I'll play with that, thanks.

**Comment by hvital** [comment]
You can also change log-parser.py lambda code to ignore counting requests from those resources (ex: ignore counting static assets requests). However, we are changing HTTP flood protection to use the new native AWS WAF Rate Based Rule (http://amzn.to/2sZCEB1) this will make it easier to add conditions to customize what/how requests should be counted. This new version will be published soon.
