### ISSUE TITLE
Template format error for us-west-1, us-east-2

### ISSUE THREAD

**Issue by hsanjuan** [awslabs/aws-waf-security-automations#24]
Hi, I am getting a:

```
Creating CloudFormation stack failed: ValidationError: Template format error: Unrecognized resource types: [AWS::WAFRegional::IPSet, AWS::WAFRegional::WebACL, AWS::WAFRegional::Rule, AWS::WAFRegional::XssMatchSet, AWS::WAFRegional::SqlInjectionMatchSet]
```

with the alb template. Any idea ?

**Comment by hvital** [comment]
Need to check the current AWS WAF for ALB support for those regions. Direct link: 
https://aws.amazon.com/pt/about-aws/global-infrastructure/regional-product-services/

**Comment by hsanjuan** [comment]
In fact, according to AWS support, there was/is a problem with AWS Cloudformation support for WAF regional not working in regions where WAF regional is supported. Manual creation of the resources via web interface worked back then.

I have no idea if this is fixed or not, but I'll close this anyway as this seems to be the wrong place for it.

**Comment by shreekarthic** [comment]
I agree with hsanjuan. 
As of today, using Cloudformation for WAFRegional in some region is currently not supported yet.

**Comment by gsdirkus** [comment]
We are in eu-central-1 where ALB and wafRegional is supported but the cloudformation does not support the Resource type.
Real pity that thsi is not working. Is there no way to get this to setup and make the lambda changes that update the lists manualy?

**Comment by vainkop** [comment]
eu-central-1 
`Template validation error: Template format error: Unrecognized resource types: [AWS::WAFRegional::IPSet, AWS::WAFRegional::WebACL, AWS::WAFRegional::Rule, AWS::WAFRegional::XssMatchSet, AWS::WAFRegional::SqlInjectionMatchSet]`

According to https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/ we should be able to do that, but no :(

**Comment by direvus** [comment]
Same here, in ap-southeast-2 (Sydney)

**Comment by theHarvester** [comment]
+1

**Comment by ctacka** [comment]
+1 in eu-central-1

**Comment by MrRager** [comment]
Same in us-east-2

**Comment by bluemalkin** [comment]
Same issue in ap-southeast-2

It would be nice if AWS made templates that actually worked !

**Comment by Hallian** [comment]
Same issue at eu-central-1

**Comment by hvital** [comment]
CloudFormation currently supports AWS WAF for ALB resources in the following regions:

• US East (N. Virginia) – us-east-1
• US West (N. California) – us-west-1
• US West (Oregon) – us-west-2
• Asia Pacific (Tokyo) – ap-northeast-1
• EU (Ireland) – eu-west-1

We are continually working on having feature parity across other regions.

**Comment by direvus** [comment]
This appears to be resolved in ap-southeast-2 (Sydney) now.  I was able to create an AWS::WAFRegional::IPSet resource

**Comment by hvital** [comment]
**UPDATE**: CloudFormation currently supports AWS WAF for ALB resources in the following regions:

• US East (N. Virginia) - us-east-1
• **US East (Ohio) - us-east-2**
• **US West (N. California) - us-west-1**
• US West (Oregon) - us-west-2
• **Asia Pacific (Sydney) - ap-southeast-2** 
• Asia Pacific (Tokyo) - ap-northeast-1
• EU (Frankfurt) - eu-central-1
• EU (Ireland) - eu-west-1

We are continually working on having feature parity across other regions.

**Comment by kryachkov** [comment]
@hvital what about `eu-north-1`?
