### ISSUE TITLE
Running the script through cloudformation stack fails to create the Custom::WafWebAclRuleControler

### ISSUE THREAD

**Issue by hamija** [awslabs/aws-waf-security-automations#3]
I am using this as a starting point. I have made very few changes, however I am attempt to build this through a cloudformation script to run automatically. When it gets to the point for creating: Custom::WafWebAclRuleControler, it will failed. When reviewing the CloudWatch logs it indicates the DescribeStacks is getting access denied. When I run the same script that was modified under: https://console.aws.amazon.com/cloudformation/home?region=us-east-1#/stacks/new?stackName=AWSWAFSecurityAutomations&templateURL=https:%2F%2Fs3.amazonaws.com%2Fsolutions-reference%2Faws-waf-security-automations%2Flatest%2Faws-waf-security-automations.template and point it towards my S3 bucket that it will run. I am trying to pinpoint why it is failing here.

![image](https://cloud.githubusercontent.com/assets/26151702/23530023/24326662-ff5d-11e6-8520-0f50c90ba597.png)

Any direction on this would be great!

Thank you,

Jay

**Comment by hvital** [comment]
Hi hamija. 

I would say that maybe this is related to Stack Name size restriction. Please note that "The stack name must be less than 25 characters, cannot contain spaces, and must be unique within your AWS account." Ref: http://docs.aws.amazon.com/solutions/latest/aws-waf-security-automations/deployment.html

**Comment by jrstarke** [comment]
@hamija: I was experiencing this as well. I changed the way the lambda get the stack name, so that it supports longer names.

This is available in pull request https://github.com/awslabs/aws-waf-security-automations/pull/5

**Comment by dexterdejesus** [comment]
Having the same issue, tested on the 2 different AWS Account  same error message, even though I change the Stack name to a Short one.

**Comment by itopiacloud** [comment]
Hi @jrstarke I've applied patch6 but still failing?

**Comment by ericjacques** [comment]
I have the same issue, but **I may found the reason**: 
The name of the bucket specified for logs during the installation is not "worldwide unique", as it's an S3 limitation, you have try with another name for "**CloudFront Access Log Bucket Name**" field.

**Please Confirm if it's working.**

Explainations:
the error in cloudWatch log is:
"An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied"
So I searched in lamda functions and there is one call in SolutionHelper for localisation:
response = s3_client.get_bucket_location(Bucket=bucket_name)
I can't run it but I suppose it will crash with "access denied" if the bucket alerady owns to someone else...

**Comment by systemsymbiosis** [comment]
Is there anyone in charge of this code base? There seem to be some good pull requests out there and a need to resolve the long stack names, support the new 10,000 reputation list length and support for both CloudFront and LoadBalancer (Regional) endpoints. It would be great to update the code to support these scenarios.

**Comment by hvital** [comment]
We just published an update with some enhancements and ALB support:
https://aws.amazon.com/answers/security/aws-waf-security-automations/

**Comment by y86** [comment]
I am still facing the original issue even after the update. Is there a workaround for now?

**Comment by hvital** [comment]
y86. I'll merge a pull request that solve this issue in the next version. Until there, the recomendadion is to use stack name with less than 25 char length.

**Comment by yveshwang** [comment]
after a mountain of frustration, found a cloudwatch log entry saying that the bucket was not created during the cloudformation process. 

fix is to create the bucket for cloud front access log before running cloud formation, ensuring it is also part of the same region. re-run cloudformation if it failed the first time. 

![screen shot 2017-10-10 at 15 54 25](https://user-images.githubusercontent.com/533023/31390222-9feb5be0-add3-11e7-8384-a8e9be2197de.png)
![screen shot 2017-10-10 at 15 54 48](https://user-images.githubusercontent.com/533023/31390230-a466bf8e-add3-11e7-89e8-d876974ad76c.png)

**Comment by shammy12** [comment]
Following yveshwang's comment, I went to create the bucket and found out that the bucket name I was trying to use was already taken. As a test, rather than create the S3 bucket, I added a unique bucket name to the Stack template, ran it again, and then it completed successfully.

**Comment by rectalogic** [comment]
@hvital 
> I'll merge a pull request that solve this issue in the next version. Until there, the recomendadion is to use stack name with less than 25 char length.

We're trying to use this as a nested stack in an existing production stack. CF generates the nested stack name by appending a the nested stack name to the main stack name plus a 12 or 13 char random suffix, and existing stacks cannot be renamed.

**Comment by badaldavda** [comment]
Hi,

This is still and issue and I was able to reproduce this. One of my customers is facing this issue. Is there any solution to this?

**Comment by KEYURRATANGHAYRA** [comment]
I have tried to follow yveshwang's workaround. I have changed the name of the s3 bucket and it worked. So I believe while creating the CFN stack native s3 API should give you the error right of the bat saying bucket name exists.

**Comment by vainkop** [comment]
I'm unable to deploy the WAF stack using Cloudformation in `eu-central-1`, but it's working in `us-east-1`.

Due to https://github.com/awslabs/aws-waf-security-automations/issues/3#issuecomment-335480780 I'm unable to use a bucket created by me (auto created by ALB) in `eu-central-1` region as it should be created by the Cloudformation.

Is there any solution, except for a non Cloudformation way?

**Comment by hatricker** [comment]
I came across this issue too. And it seems it's due to global uniqueness of S3 bucket name. After I changed the S3 bucket name, the creation succeeded.
![screenshot from 2018-08-02 10-57-08](https://user-images.githubusercontent.com/2794239/43601880-3c041794-9643-11e8-953e-40e1baaf1739.png)

**Comment by keyurvala** [comment]
Tired find the solution of it 
" Your access has been denied by S3, please make sure your request credentials have permission to GetObject for /aws-waf-security-automations/v2.3.3/helper.zip. S3 Error Code: AccessDenied. S3 Error Message: Access Denied (Service: AWSLambdaInternal; Status Code: 403; Error Code: AccessDeniedException; Request ID: 
![1-1](https://user-images.githubusercontent.com/17255668/91077700-24afbd00-e65f-11ea-8859-8b8d8be16167.PNG)
