### ISSUE TITLE
CREATE_FAILED -- AWS::IAM::Role -- SolutionHelperRole

### ISSUE THREAD

**Issue by techmag** [awslabs/aws-waf-security-automations#33]
Third times usually a charm however I seem to be stuck here: 

API: iam:CreateRole User: arn:aws:sts::xxxxxxxxxxxxxxxx:assumed-role/Technical-Magic-AWS-WAF-Role/AWSCloudFormation is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::xxxxxxxxxxxxxxxxx:role/Technical-Magic-AWS-WAF-Stack-SolutionHelperRole-XXXXXXXXXXXXXXX

I have created a Role (Technical-Magic-AWS-WAF-Role) and assigned the policy: arn:aws:iam::aws:policy/AWSWAFFullAccess and pointed to it during the initial configuration phase of the Stack template however I'm stumped as to how to move forward with this. 

There is no iam:CreateRole in the list of polices. I do see an IAMFullAccess but unsure if that is too powerful. Perhaps if I use that on a temp basis it might work? I HATE guessing however. 

What are the (minimum) Roles that need to be assigned in order to implement this stack please?

**Comment by techmag** [comment]
Seems I'm managing to muddle through this with inline policies. 

This helped; https://superuser.com/questions/1160065/aws-allow-user-to-call-create-role

**Comment by techmag** [comment]
This, (Template validation error: Parameter 'CloudFrontAccessLogBucket' must match pattern (^$|^([a-z]|(\d(?!\d{0,2}\.\d{1,3}\.\d{1,3}\.\d{1,3})))([a-z\d]|(\.(?!(\.|-)))|(-(?!\.))){1,61}[a-z\d]$)) in english, just means lower case :) 

That one I knew already...

**Comment by techmag** [comment]
This statement does not appear to be correct: This can be the name of either an existing S3 bucket, or a new bucket that the template will create during stack launch (if it does not find a matching bucket name). 

It appears it IS looking for an exciting bucket. 

![cursor_and_cloudformation_management_console](https://user-images.githubusercontent.com/2105782/31050056-51a44df6-a60e-11e7-9046-26ad99e19217.png)

**Comment by techmag** [comment]
Dead end: 

CREATE_FAILED | AWS::Lambda::Function | LambdaWAFBadBotParserFunction | Error occurred while GetObject. S3 Error Code: NoSuchBucket. S3 Error Message: The specified bucket does not exist
-- | -- | -- | --

Might be helpful if the bucket name was echoed. 

Bucket name does not appear to be in the CloudWatch logs either. 

Not expecting anyone other than me to resolve this just reflecting what one person's (end user) experience of trying to implement this is like. Way beyond painful thus far...

Was hoping to be helpful to others hitting similar dead ends. 

Thus far we have the following Policies (so perhaps others can side-step that bucket of pain...): 

AWSLambdaFullAccess
AmazonS3FullAccess
AmazonAPIGatewayInvokeFullAccess (guess)
AWSWAFFullAccess

Plus these two inline policies:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1482712489000",
            "Effect": "Allow",
            "Action": [
                "iam:CreateRole",
                "iam:GetRole",
                "iam:DeleteRole",
                "iam:DeleteRolePolicy",
                "iam:PutRolePolicy"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}`

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1467321765000",
            "Effect": "Allow",
            "Action": [
                "apigateway:*"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}`


![cloudformation_management_console](https://user-images.githubusercontent.com/2105782/31050140-34f5243a-a610-11e7-9a6d-260ce4d81947.png)

**Comment by techmag** [comment]
I have moved to AWS Paid Technical support and am attempting to resolve this through them now.

**Comment by techmag** [comment]
Ah - apparently there is a prebuilt version of this and the build instructions here are in fact not required:  AWS CloudFormation Templates - http://docs.aws.amazon.com/solutions/latest/aws-waf-security-automations/template.html

That seems to be working thus far. Will confirm once complete.

**Comment by hvital** [comment]
Hi, is the solution working now? Reading the comment, it might be related to: "The stack name must be less than 25 characters, cannot contain spaces, and must be unique within your AWS account."

We're merging some pull requests to remove this limitation for the next release.

**Comment by techmag** [comment]
That, the 25 character limit, was exactly the problem. Apparently I can be too verbose at times :) 

WAF is up and running and I've started migrating my assets to live "behind" it's protective voodoo now... 

Curious as to how "upgrades" are handled as the WAF stack improves. Could you point me in the correct direction to prepare for that please?
