### ISSUE TITLE
Write of 

### ISSUE THREAD

**Issue by jmstallard** [awslabs/aws-waf-security-automations#35]
Hi - 
great work!
I'm getting a write failure (403) from Log-parser.py line 153:
 response = s3.head_object(Bucket=environ['OUTPUT_BUCKET'], Key=OUTPUT_FILE_NAME)
>> An error occurred (403) when calling the HeadObject operation: Forbidden

I see the bucket *does* exist and the IAM policy is set to   "Action": "s3:PutObject" for the upload file:
aws-waf-security-automations-current-blocked-ips.json

No errors from the download operation.

Any ideas?
Everything else is working great.

**Comment by jrstarke** [comment]
Maybe I'm misunderstanding something, but wouldn't the log parser need `s3:GetObject` as well?

**Comment by jmstallard** [comment]
Thanks, Jamie -

Yes, and that is set for everything under the CloudFront bucket:

 "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::<sba-cloudfront-bucket>/*",
            "Effect": "Allow"

So, I'll put in some print statements to see what's up


________________________________

**Comment by jmstallard** [comment]
OK - somewhat a false alarm -


I created an empty json file on the s3 bucket:

aws-waf-security-automations-current-blocked-ips.json


works fine now - except, a separate pb. - send_anonymous throws errors due to no rules found... probably should be Warning or Info.


-JMS


________________________________

**Comment by jmstallard** [comment]
all good
