### ISSUE TITLE
Suggestion: Parameterize bucket name, include yaml files

### ISSUE THREAD

**Issue by jmstallard** [awslabs/aws-waf-security-automations#37]
To simplify deployment, I suggest configuring the Bucket Name as a parameter instead of generating new templates. I've a pull request with the updates. Also added yaml files & a generator script for those that prefer yaml.

**Comment by stevemorad** [comment]
This feature request has been incorporated into the next version.

**Comment by jmstallard** [comment]
Great! Thanks much.
