### ISSUE TITLE
TorProject ExitAddresses do not match regex in reputations lists parser

### ISSUE THREAD

**Issue by cmilam87** [awslabs/aws-waf-security-automations#40]
https://github.com/awslabs/aws-waf-security-automations/blob/beca5eb31b55dcba291b5ad1a91a0ba687292402/source/reputation-lists-parser/reputation-lists-parser.js#L112

The regular expression there does not match the TorProjects list of ExitAddresses: https://check.torproject.org/exit-addresses

**Comment by hvital** [comment]
Hi @cmilam87. 

@dgtanner sent a [PR](https://github.com/awslabs/aws-waf-security-automations/pull/69) to fix this. 

btw, do you know a sample of an [exite-address](https://check.torproject.org/exit-addresses) that was failing to be imported before this fix? Would like to add a new test case to cover this.

**Comment by cmilam87** [comment]
@hvital - any of them I believe. It's because there was a space in the exit-addresses

**Comment by hvital** [comment]
@cmilam87 

Code edited [here](https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/source/reputation-lists-parser/reputation-lists-parser.js#L113) to reflect the change suggested in [PR#69](https://github.com/awslabs/aws-waf-security-automations/pull/69)
