### ISSUE TITLE
Rules not attaching on latest commit for ALB WAF....

### ISSUE THREAD

**Issue by davidadixon** [awslabs/aws-waf-security-automations#41]
The only rule I see *attach* to the ACL on this when the build is done is the whitelist rule.  The other rules exist but are not attached.  You can attach them manually.

**Comment by davidadixon** [comment]
Scratch that.  Seems to be something that I am doing, not the template.  I apologize.

**Comment by jasonmcintosh** [comment]
Seen similar behavior myself, so may still be something in this stack.  Haven't figured out WHY or when this happens yet.
