### ISSUE TITLE
Changing CrossSiteScriptingProtectionParam to "no" does not delete XSS rule

### ISSUE THREAD

**Issue by rectalogic** [awslabs/aws-waf-security-automations#43]
If the existing stack has CrossSiteScriptingProtectionParam set to "yes", changing it to "no" and updating the stack results in an error:

```
DELETE_FAILED | AWS::CloudFormation::ManagedCustomResource | WAFXssRule | This entity is still referenced by other entities. (Service: AWSWAFRegional; Status Code: 400; Error Code: WAFReferencedItemException; Request ID: eb82f55e-e65b-11e7-852c-f5cacd8acf32)
```

However the stack ends in an UPDATE_COMPLETE state with reason "Update successful. One or more resources could not be deleted." and the XSS rule is still enabled in the WebACL and must be manually removed.

**Comment by hvital** [comment]
Hi @rectalogic 

We've just pushed a new version. The custom resource was reviewed to avoid update issues like the one you've mentioned. 

PS: Please note that the only update that is not support is when you try to change ALB stack to/from CloudFront. During such type of update, the Lambdas' permissions are changed ('waf-regional' to/from 'waf') and this lead us to permission error when deleting old resources. 

The recommended approach, if you want to switch an ALB stack to/from CloudFront, is to delete and recreate a new stack.
