### ISSUE TITLE
ALB scan/probe parser looking at wrong response code

### ISSUE THREAD

**Issue by rectalogic** [awslabs/aws-waf-security-automations#44]
It looks like the scan/probe parser is looking at field 8 which is elb_status_code instead of 9 which is target_status_code
https://github.com/awslabs/aws-waf-security-automations/blob/master/source/log-parser/log-parser.py#L47

We had a situation where the HTTP Flood rule kicked in and blocked an IP, so all of the ALB logs elb_status_code were 403 and target_status_code was "-". It appears the scan/probe parser then read those ALB 403s as bad requests and also kicked in blocking that IP.

I think it should only look at target_status_code for 4xx

**Comment by celalo** [comment]
It's the same issue with Cloudfront scan/probe parser: https://github.com/awslabs/aws-waf-security-automations/blob/master/source/log-parser/log-parser.py#L39

**Comment by hvital** [comment]
Hi @rectalogic. 

We've just pushed a new version that includes a fix for what you've mentioned:
https://github.com/awslabs/aws-waf-security-automations/blob/c7b25b4f9005469f1606e8da19c9704268f0697a/source/log-parser/log-parser.py#L50

Regards, 

PS: I haven't found an equivalent filed for CloudFront access logs.
