### ISSUE TITLE
stack design issues

### ISSUE THREAD

**Issue by ghost** [awslabs/aws-waf-security-automations#45]
The rules' metric names (MetricName) are not unique. When multiple stacks are used metrics become unusable. Multiple stacks are necessary for CI/CD but also required sometimes because of the way flood protection works. Lambda code also reference these hard coded metric names

There is a similar problem with the bucket event. When trying to do an A/B deployment of the WebACL the bucket configuration will fail for the new stack because the id is not unique. The s3 trigger configuration id is hard coded to "Call Log Parser". It should be prefixed with the stack name or some other unique identifier

Almost everyone needs to customize the stack but while it is an excellent starting point there are many things to fix and this makes it really hard to merge changes. It is an excellent first incarnation but will require a redesign at some point to make it easier to customize and update.

**Comment by hvital** [comment]
I saw a pull request about that (PR#53). Good catch.

Set to be included in the next release. 

Thanks!!

**Comment by hvital** [comment]
We've just pushed a new version that includes the PR#53. 

Thanks!
