### ISSUE TITLE
Does not work for ALB in Sydney Region

### ISSUE THREAD

**Issue by aharps** [awslabs/aws-waf-security-automations#48]
When i try to use this template 

https://s3.amazonaws.com/solutions-reference/aws-waf-security-automations/latest/aws-waf-security-automations-alb.template
in the Sydney Region I get the following error

Template validation error: Template format error: Unrecognized resource types: https://forums.aws.amazon.com/

I can use it in other regions.

Does anyone know why this is ?

**Comment by johnbrandborg** [comment]
Just got this too.  I don't understand how the resource types aren't support!

**Comment by MattTunny** [comment]
+1 for sydney region please

**Comment by vainkop** [comment]
+1 for `eu-central-1`

**Comment by edit-michael** [comment]
+1 for eu-central-1 region please

**Comment by hvital** [comment]
**UPDATE**: CloudFormation currently supports AWS WAF for ALB resources in the following regions:

• US East (N. Virginia) - us-east-1
• US East (Ohio) - us-east-2
• US West (N. California) - us-west-1
• US West (Oregon) - us-west-2
• **Asia Pacific (Sydney) - ap-southeast-2**
• Asia Pacific (Tokyo) - ap-northeast-1
• **EU (Frankfurt) - eu-central-1**
• EU (Ireland) - eu-west-1

We are continually working on having feature parity across other regions.
