### ISSUE TITLE
Stack continously fails to create

### ISSUE THREAD

**Issue by ShadySQL** [awslabs/aws-waf-security-automations#49]
Got this error: 

An error occurred (InvalidArgument) when calling the PutBucketNotificationConfiguration operation: Configuration is ambiguously defined. Cannot have overlapping suffixes in two rules if the prefixes are overlapping for the same event type.

Have no clue what this means but I think its not able to create the s3 events on that bucket. The bucket aleady exists. This CFN template has an input parameter for a bucket on s3 for alb logging - I give that but this thing doesn't work.

**Comment by eric5102** [comment]
Look at the events you already have on this bucket and look at the related S3 documentation

> Notification configurations that use Filter cannot define filtering rules with overlapping prefixes, overlapping suffixes, or prefix and suffix overlapping. The following sections have examples of valid notification configurations with object key name filtering and examples of notification configurations that are invalid because of prefix/suffix overlapping.

Ref: https://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html

**Comment by ShadySQL** [comment]
? The only event I have for this bucket is to stream to an existing Lambda function for ObjectCreate (All). I dont understand the problem here.

**Comment by eric5102** [comment]
Your event must have an empty prefix to trigger for ObjectCreate (All). You can't have 2 events with overlapping prefixes so you have a conflict. If you do need the overlap you have to modify the deployed architecture to fan out the event and filter the message elsewhere. This can be done many ways:
1. trigger a Lambda function that filters then routes to the appropriate Lambda target
2. trigger SNS instead and subscribe your 2 lambda functions to it
3. trigger SNS but use the new event filtering (https://docs.aws.amazon.com/sns/latest/dg/message-filtering.html) to subscribe the Lambda functions only to events they care about

IMHO aws-waf-security-automations is a sample implementation and can't really be used as-is. It has many implementation flaws and limitations (some of which are inherited from the WAF itself like limited CIDR support and no support for rule groups). Hopefully it will evolve over time and be restructured into nested templates that are easier to maintain but in its current state it is difficult to merge any change you need with fixes added to the main branch. It is however a great start and provides the basics for a good implementation.

**Comment by fabioce** [comment]
My error
LambdaWAFBadBotParserFunction | 1  validation error detected: Value '%%BUCKET_NAME%%-eu-west-1' at  'code.s3Bucket' failed to satisfy constraint: Member must satisfy  regular expression pattern: ^[0-9A-Za-z\.\-_]*(?<!\.)$
-- | --

**Comment by hvital** [comment]
We've just pushed a new version. Custom resource now was broken down into small resources and the error messages were reviewed to help you troubleshoot access log bucket configuration problems. 

https://github.com/awslabs/aws-waf-security-automations/blob/c7b25b4f9005469f1606e8da19c9704268f0697a/source/custom-resource/custom-resource.py#L50

Thanks!
