### ISSUE TITLE
Automated Deployment of WAF in eu-central-1 (Frankfurt) is always failing with failure to create Custom::WafWebAclRuleControler. It works in US East (N. Virginia) us-east-1.

### ISSUE THREAD

**Issue by vainkop** [awslabs/aws-waf-security-automations#51]
Automated Deployment of WAF in `eu-central-1` (Frankfurt) is always failing with failure to create Custom::WafWebAclRuleControler. It works in `us-east-1` (N. Virginia) though.

If I try to use an S3 bucket `in us-east-1` which is created by Cloudformation deployment then I can't use this bucket for my ALB in `eu-central-1` region, so I can't use this solution https://github.com/awslabs/aws-waf-security-automations/issues/3#issuecomment-335480780

If I create a bucket in `eu-central-1` region myself (or auto create with ALB) then the Cloudformation deployment in is failing with the same `Custom::WafWebAclRuleControler` error.

The Cloudformation stack is unique & short enough (less than 25 symbols) `awswafwx975251` according to recommendation https://github.com/awslabs/aws-waf-security-automations/issues/3#issuecomment-317033924

The name of the S3 bucket for logs is also unique & short enough (less than 25 symbols) `prodapplbwx975251`

**Comment by hvital** [comment]
We've just pushed a new version that we tested in the following regions:

**ALB Version**
- US East (N. Virginia)
- US East (Ohio)
- US West (N. California)
- US West (Oregon)
- EU (Ireland)
- EU (Frankfurt)
- Asia Pacific (Sydney)
- Asia Pacific (Tokyo)

**CloudFront Version**
- US East (N. Virginia)
- US East (Ohio)
- US West (N. California)
- US West (Oregon)
- EU (Ireland)
- EU (Frankfurt)
- Asia Pacific (Sydney)
- Asia Pacific (Tokyo)
- Asia Pacific (Mumbai)
- Asia Pacific (Seoul)
- Asia Pacific (Singapore)
- Canada (Central)
- EU (London)
- EU (Paris)
- EU (Stockholm)
- South America (Sao Paulo)

It should work on eu-central-1.

Regards.
