### ISSUE TITLE
IPV6 support in log_parser

### ISSUE THREAD

**Issue by vr00n** [awslabs/aws-waf-security-automations#57]
Ref: #23 - Not addressed in log_parser code. Resulting in tons of CloudTrail errors as the lambda is trying to add IPV6/32 instead of IPV6/128

```
"errorMessage": "Update failed, invalid CIDR block: cannot parse IPV6/32 as a CIDR"
```

Thanks

**Comment by vr00n** [comment]
Created a pull request for this Rrf: #58

**Comment by hvital** [comment]
Hi, 

I saw the PR related to this. Added to be considered for the next release. 

MANY thanks for the contribution.

**Comment by hvital** [comment]
Hi @vr00n. 

We've just pushed a new version with IPv6 for LogParser included. 

Thanks!
