### ISSUE TITLE
custom-resource.py overrides DefaultAction

### ISSUE THREAD

**Issue by dpmallinger** [awslabs/aws-waf-security-automations#63]
if you change the WAF default action in the cloudformation the WAF is initially created with that default action but it is then overrridden when custom-resource.py runs.

                response = waf.update_web_acl(
                    WebACLId=web_acl_id,
                    ChangeToken=waf.get_change_token()['ChangeToken'],
                    Updates=updates,
                    DefaultAction={'Type': 'ALLOW'}
                )

Can the line be removed so this confusion is removed and the cloudformation value is honored?

**Comment by hvital** [comment]
This default action should apply for Web ACL’s default action. I mean, if any rule got trigged when a request is process, then the default action takes place. 

The rules configured by custom resource are set to be added as block ... what if we add an extra input parameter in this template to ask what should be the rules’ action?

**Comment by dpmallinger** [comment]
Hello,

I have a custom scenario where I want the default action to be "BLOCK".  I updated the cloudformation

"WAFWebACL": {
      "Type": "AWS::WAF::WebACL",
      "Condition": "CreateWebACL",
      "DependsOn": [
        "WAFWhitelistRule"
      ],
      "Properties": {
        "Name": {
          "Ref": "AWS::StackName"
        },
        "DefaultAction": {
          "Type": **"BLOCK"**
        },
        "MetricName": "SecurityAutomationsMaliciousRequesters",
        "Rules": [
          {
            "Action": {
              "Type": "ALLOW"
            },
            "Priority": 10,
            "RuleId": {
              "Ref": "WAFWhitelistRule"
            }
          }
        ]
      }
    },

but once custom-resource.py runs it changes it to "ALLOW".

I don't see a need for this line in the python script
DefaultAction={'Type': 'ALLOW'}

why not simply honor the cloudformation value?

**Comment by hvital** [comment]
I got your point! 

We can't remove this parameter from [update_web_acl](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/waf.html#WAF.Client.update_web_acl) as it seems to be required but I'll add an extra step to retrieve the current action instead assuming the it should be ```ALLOW```.

**Comment by dpmallinger** [comment]
@hvital 

how I read the documentation is that if "DefaultAction" is passed then "Type" is required but I don't believe that "DefaultAction" is required

**Comment by hvital** [comment]
I miss understood the ```Type (string) -- [REQUIRED]``` boto doc. Lets just remove this parameter then :)

Just added a note to include this for the next update. Thanks for pointing this out!!

**Comment by dpmallinger** [comment]
thanks!
