### ISSUE TITLE
Inconsistent "aws-waf-security-automations-alb.template" 

### ISSUE THREAD

**Issue by gary-tsai-zocdoc** [awslabs/aws-waf-security-automations#65]
Hi,

After multiple deployments of CloudFormation stack using aws-waf-security-automations-alb.template, i realized there are 2 versions of the template. 

Template from [docs.aws.amazon.com](https://docs.aws.amazon.com/solutions/latest/aws-waf-security-automations/template.html) is different than Github [awslabs/aws-waf-security-automations/deployment/](https://github.com/awslabs/aws-waf-security-automations/blob/master/deployment/aws-waf-security-automations-alb.template).

I jumped to search for WAF template in Github directly discovered the stack fails to build when using Github version.

Please address the differences as this can cause potential confusion.

**Comment by hvital** [comment]
Thanks  gary-tsai-zocdoc, 

We're going to check this differences and update the repo when we publish the next version. 

In the meantime, please keep using the templates you've commented: https://docs.aws.amazon.com/solutions/latest/aws-waf-security-automations/template.html

**Comment by hvital** [comment]
Hi @gary-tsai-zocdoc 

We've just pushed a new version and updated the solution's doc page. The template should be the same now. 

Thanks!
