### ISSUE TITLE
Different region

### ISSUE THREAD

**Issue by alfaro28** [awslabs/aws-waf-security-automations#7]
How do I choose the region for the ACL and rules, right now it uses cloudfront (global) but I need to use it on ALB in us-east.

**Comment by jtanton** [comment]
Ditto.  Is there an effort to allow this solution to be implemented into a single region?  I don't want or need cloudfront in this solution, but my security group requires a WAF be in front of my public facing app.

**Comment by itopiacloud** [comment]
It'd be frighteningly useful if there were corresponding zips for supporting waf regional for elbv2 please, rather than modifying/s3'ing/rolling my own :)

**Comment by itopiacloud** [comment]
Have forked this to support waf/elbv2 @jtanton @alfaro28

**Comment by hvital** [comment]
We just published an update with ALB support:
https://aws.amazon.com/answers/security/aws-waf-security-automations/

**Comment by stevemorad** [comment]
Fixed in v2.1
