### ISSUE TITLE
Vulnerability Found issu

### ISSUE THREAD

**Issue by babujigr** [awslabs/aws-waf-security-automations#70]
Hi,

When i try to do deployment as per the instruction, I am getting result of 
"found 64 vulnerabilities (11 low, 39 moderate, 14 high) in 4042 scanned packages
  run `npm audit fix` to fix 1 of them."
I tried to updated npm but no luck, I am running with npm 6.4.1 & node 8.15

I am not a developer and new to this Git. Just wanted to check, will those vulnerabilities cause any issue if i use this waf template? Kindly suggest.

**Comment by hvital** [comment]
Hi @babujigr 

We're working on an update and will include to review the output of npm audit for the Node component. 

Thanks for reporting this!
