### ISSUE TITLE
Issue with S3 bucket location constraint

### ISSUE THREAD

**Issue by brianwthomas** [awslabs/aws-waf-security-automations#72]
There's an issue with setting the S3 client region in the custom-resource.py file when using older buckets in eu-west-1 region.

https://github.com/awslabs/aws-waf-security-automations/blob/master/source/custom-resource/custom-resource.py

We need to change this:
```
if response['LocationConstraint'] == None:
    response['LocationConstraint'] = 'us-east-1'
if response['LocationConstraint'] != region:
    raise Exception('Bucket located in a different region. S3 bucket and Log Parser Lambda (and therefore, you CloudFormation Stack) must be created in the same Region.')
```

To
```
if response['LocationConstraint'] == None:
    response['LocationConstraint'] = 'us-east-1'
if response['LocationConstraint'] == 'EU':
    response['LocationConstraint'] = 'eu-west-1'
if response['LocationConstraint'] != region:
    raise Exception('Bucket located in a different region. S3 bucket and Log Parser Lambda (and therefore, you CloudFormation Stack) must be created in the same Region.')
```

see the S3 region constraints located here: https://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region
eu-west-1 is a special case which can return either eu-west-1 or EU as a location constraint.

**Comment by hvital** [comment]
@brianwthomas 

New check added [here](https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/source/helper/helper.py#L75).

Please note that we've moved all dependencies and pre-req check to be validated before creating other template's resources. More info [here](https://github.com/awslabs/aws-waf-security-automations/blob/e504013c87bde6d6af434097f0c1147a4c1f86c0/deployment/aws-waf-security-automations.template#L304)
