### ISSUE TITLE
Webinar/office-hours  about this implementation

### ISSUE THREAD

**Issue by ravsau** [awslabs/aws-waf-security-automations#73]
Hi, I've been making use of this template to setup WAF for our project and It's been super helpful. 
I still have many questions and would love to learn more about how the whole app is setup. 

I also saw that this solution is part of  newly released https://aws.amazon.com/solutions/ 

So I was wondering , if there's plans for any office hours like some other AWS services have? Or a Webinar where we can ask questions etc.

**Comment by hvital** [comment]
Hi @ravsau. 

You can open a support ticket (https://console.aws.amazon.com/support/cases#/create) and add a link to this repository inside the case description.

With that, the ticket will be redirected to our group and we can answer your questions there or schedule a call. 

Regards,

**Comment by ravsau** [comment]
@hvital Thanks for the reply. I'll open a support ticket soon.
