### ISSUE TITLE
Add partitioning on app_access_logs

### ISSUE THREAD

**Issue by jmonson** [awslabs/aws-waf-security-automations#84]
Any plans to add partitioning to the Athena Log Parser? Perhaps the Lambda Log Parser could create a new partition on each invocation, thus limiting the need to scan all ELB logs? I'm worried the query is going to start getting really slow in the future.

**Comment by hvital** [comment]
Thanks for sharing your feedback. This was included to the solution roadmap and we'll post an update to this thread once we have more information.

In the meantime, I suggest reading the references I mentioned on [Issue#92](https://github.com/awslabs/aws-waf-security-automations/issues/92)

**Comment by rakshb** [comment]
Hello @jmonson We have addressed this issue in V2.3.3 released recently
