### ISSUE TITLE
Raising reputation list to support the new 10000 ip per ipset

### ISSUE THREAD

**Issue by nokiomanz** [awslabs/aws-waf-security-automations#9]
Hi, 

Yesterday I came across this news : 
https://aws.amazon.com/about-aws/whats-new/2017/05/limit-increase-for-ipset-conditions-for-aws-waf/

The limit per ipset was increased to from 1000 to 10 000 about a month ago. 
The reputation list parser has not been updated to reflect that change and so both list #1 and #2 still only include up to 1000 ip. 

Looking at : 
https://github.com/awslabs/aws-waf-security-automations/blob/master/code/reputation-lists-parser/reputation-lists-parser.js
We can see the variable "var maxDescriptorsPerIpSet = 1000;"
I changed it directly in my lambda function to "var maxDescriptorsPerIpSet = 10000;"
Waited 1 hour for the function tu run again. And it seems to work perfectly.

Before we only had 2 000 entry in the 2 ipset and now I have the whole close to 12 000 entry. 
Could it be interesting to update this template to reflect that change?

**Comment by jrstarke** [comment]
@nokiomanz: I think this would be a valuable change, I know it's something that I would use personally.

**Comment by hvital** [comment]
We just published an update considering this new limit:
https://aws.amazon.com/answers/security/aws-waf-security-automations/

**Comment by nokiomanz** [comment]
I will close this as it is not needed anymore.
Thanks!
