### ISSUE TITLE
Cost associated with deploying stack

### ISSUE THREAD

**Issue by antonsamper** [awslabs/aws-waf-security-automations#92]
Can anyone provide the current daily or monthly cost associated with deploying this stack  with all the WAF rules turned on?

**Comment by hvital** [comment]
Hi @antonsamper 

This [blog post](https://aws.amazon.com/blogs/devops/tracking-the-cost-of-your-aws-cloudformation-stack/) is a little bit old but might help you check how to track cost by cloudformation tag. 

If you are using Athena log parser, I strongly recommend reviewing those references:
- https://aws.amazon.com/blogs/big-data/analyze-your-amazon-cloudfront-access-logs-at-scale/
- https://aws.amazon.com/blogs/big-data/top-10-performance-tuning-tips-for-amazon-athena/
- https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-kinesis-data-firehose-announces-support-for-custom-amazon-s3-prefixes/

You can use something like this as kinesis prefix:
```
Prefix: 'AWSLogs/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/'
ErrorOutputPrefix: 'AWSErrorLogs/result=!{firehose:error-output-type}/year=!{timestamp:yyyy}/month=!{timestamp:MM}/day=!{timestamp:dd}/hour=!{timestamp:HH}/'
```

**Comment by antonsamper** [comment]
I've also come across [Estimating the Cost of Your CloudFormation Stack](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-paying.html) but for some reason it isn't working with this particular template.
