### ISSUE TITLE
Node.js 8.10 is EOL

### ISSUE THREAD

**Issue by edit** [awslabs/aws-waf-security-automations#99]
Dear AWSlabs Team,

Node.js 8.10 is EOL and AWS wants to disable Lambda update functions with Node.js 8.10 beginning in february 2020. Are the Node.js 8.10 functions also executable under Node.js 10.x?

**Comment by krlnwll** [comment]
Based on my testing updates will be needed to make this compatible with Node.js 10.x.

**Comment by aldegoeij** [comment]
is any effort underway updating Node?

**Comment by beomseoklee** [comment]
Thanks for your input. We are trying to update the solution with Node.js 10.X in this year.

**Comment by cccassidy** [comment]
I updated the Lambda function to Node 10.x manually in the console without any code changes and it seems to have run successfully since then.  What issues did you all run into that were incompatible with 10.x?

**Comment by krlnwll** [comment]
I am seeing some issues with async not being found.

**Comment by krlnwll** [comment]
@cccassidy What versions of async do you have? I suspect anyone with an older version is seeing this issue.

**Comment by edit** [comment]
> I updated the Lambda function to Node 10.x manually in the console without any code changes and it seems to have run successfully since then. What issues did you all run into that were incompatible with 10.x?

I changed manually the function to Node 10.x in the console too and published this as new version. The logs in cloudwatch looks for me okay. I has compare the new logs with the Node.js 8.x version and for me are the same results. In the monitoring i can't see any errors. 

Is it really so simple, or am I overlooking something?

**Comment by Jun711** [comment]
It has been updated. You have to redeploy and delete existing resources manually.

```
Version 2.3.1 of the solution uses the most up-to-date Node.js runtime. 
Version 2.3 uses the Node.js 8.10 runtime, which reaches end-of-life on December 31, 2019. 
To upgrade to version 2.3.1, you must deploy the solution as a new stack.
```

https://aws.amazon.com/solutions/aws-waf-security-automations/

**Comment by georgebearden** [comment]
Closing this issue as the solution has been updated to later version of Node, but please let us know if you need additional assistance.

**Comment by PeteAUK** [comment]
@georgebearden Sorry to ask but as somebody who installed WAF out of the box using the console wizard, how do I go about upgrading my reputation list parser so that I'm running on Node.js v10?  Not had to dig around with the inner workings of WAF beyond a couple of tweaks so am running blind currently.
